
name: Example Workflow

on:
  workflow_dispatch:  # 👈 This is required for manual triggering

jobs:
  example_job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Input
        run: echo "Input received: ${{ github.event.inputs.user_input }}"

